code_generator = new function() {
	this.genParams = function(l) {
		var s = "";
		if(l[0] == "transform") {
			for(var i = 1; i < l.length; i++){
				if(i == 1) {
					s += "pos,"
				} else {
					if(l[i][0] == "vec2") {
						s += "new vec2(" + l[i][1] + "," +l[i][2] + ")" + ",";
					} else if(l[i][0] == "string") {
						s += "\"" + l[i][1] + "\"" + ",";
					} else {
						s += l[i][1] + ",";
					}
				}
			}
		} else {
			for(var i = 1; i < l.length; i++){
				if(l[i][0] == "vec2") {
					s += "new vec2(" + l[i][1] + "," +l[i][2] + ")" + ",";
				} else if(l[i][0] == "string") {
					s += "\"" + l[i][1] + "\"" + ",";
				} else {
					s += l[i][1] + ",";
				}
			}
		};
		s = s.substring(0, s.length-1);
		return s;
	};

	this.genHtml = function(a) {
		var c = "";
		var s = "<style>\n#screen {\nposition:absolute;\ntop:0px;\nleft:0px;\ndisplay: none;\n}\n#canvas {\nposition:absolute;\ntop:0px;\nleft:0px;\n}\n</style>\n"
		var i = "<script src=\"vector.js\"></script>\n<script src=\"input.js\"></script>\n<script src=\"messages.js\"></script>\n<script src=\"actor.js\"></script><script src=\"prefab.js\"></script>\n<script src=\"scene.js\"></script>\n<script src=\"components.js\"></script>\n<script src=\"physics.js\"></script>\n<script src=\"core.js\"></script>\n\n"
		c += "<!-- Code generated by cdqwertzs Game Engine (https://github.com/cdqwertz/engine) -->\n<html>\n<head><title>Game</title>"+s+"</head>\n<body onload=\"onInit();\">\n<canvas id=\"screen\"></canvas><canvas id=\"canvas\"></canvas>\n\n"+i+"<script>\n"+a+"\n</script></body></html>"
		return c;
	};

	this.genCode = function() {
		var c = event_editor.genCode();
		for(var i = 0; i < prefab_editor.prefabs.length; i++){
			c += "\tvar " + prefab_editor.prefabs[i][0] + " = new prefab(function(pos) {\n\t\tvar obj = new actor();\n" ;
			for(var j = 1; j < prefab_editor.prefabs[i].length; j++){
				c += "\t\tobj.addComponent(new " + prefab_editor.prefabs[i][j][0] + "(" + this.genParams(prefab_editor.prefabs[i][j]) + "));\n" ;
			}
			c += "\n\t\treturn(obj);\n\t});\n\n" ;
		}
		
		c +=  "\n\n\n\tfunction load() {\n";
		
		for(var i = 0; i < level_editor.scenes.length; i++){
			for(var j = 1; j < level_editor.scenes[i].length; j++){
				c += "\t\tmainScene.addObject(" + level_editor.scenes[i][j][0] + ".build(new vec2("+ level_editor.scenes[i][j][1] + "," + level_editor.scenes[i][j][2] + ")));\n" ;
			}
		}
		c += "\t}";
		return c;
	};
}();
