code_generator = new function() {
	this.genParams = function(l) {
		var s = "";
		for(var i = 1; i < l.length; i++){
			if(l[i][0] == "vec2") {
				s += "new vec2(" + l[i][1] + "," +l[i][2] + ")" + ",";
			} else if(l[i][0] == "string") {
				s += "\"" + l[i][1] + "\"" + ",";
			} else {
				s += l[i][1] + ",";
			}
		}
		s = s.substring(0, s.length-1);
		return s;
	};

	this.genHtml = function(a) {
		var c = "";
		var s = "<style>\n#screen {\nposition:absolute;\ntop:0px;\nleft:0px;\n}\n</style>\n"
		var i = "<script src=\"vector.js\"></script>\n<script src=\"input.js\"></script>\n<script src=\"messages.js\"></script>\n<script src=\"actor.js\"></script>\n<script src=\"scene.js\"></script>\n<script src=\"components.js\"></script>\n<script src=\"physics.js\"></script>\n<script src=\"core.js\"></script>\n\n"
		c += "<!-- Code generated by cdqwertzs Game Engine (https://github.com/cdqwertz/engine) -->\n<html>\n<head><title>Game</title>"+s+"</head>\n<body onload=\"onInit();\">\n<canvas id=\"screen\"></canvas>\n\n"+i+"<script>\n"+a+"\n</script></body></html>"
		return c;
	};

	this.genCode = function() {
		var c = event_editor.genCode() + "function load() {\n";
		for(var i = 0; i < level_editor.scenes.length; i++){
			for(var j = 1; j < level_editor.scenes[i].length; j++){
				c += "\tvar " + level_editor.scenes[i][j][0] + " = new actor();\n" ;
				for(var k = 1; k < level_editor.scenes[i][j].length; k++){
					c += "\t" + level_editor.scenes[i][j][0] + ".addComponent(new " + level_editor.scenes[i][j][k][0] + "(" + this.genParams(level_editor.scenes[i][j][k]) + "));\n" ;
				}
				c += "\tmainScene.addObject(" + level_editor.scenes[i][j][0] + ");\n\n" ;
			}
		}
		c += "}";
		return c;
	};
}();
